apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ubuntu
    spec:
      volumes:
        - name: os-release
          hostPath:
            path: /etc/os-release
      containers:
      - image: vish/container-from-scratch@sha256:98ed9651d8b3e39bd505fb52f6020f5889d99e5baed21b1050f9b67ad3ff6f90
        volumeMounts:
          - name: os-release
            mountPath: /rootfs/etc/os-release
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 500Mi
        name: ubuntu
        securityContext:
          privileged: true
        stdin: true
        tty: true
      restartPolicy: Always
      